# Generated by Django 2.2.4 on 2019-10-13 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191013_0552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follow_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.CharField(max_length=50)),
                ('follow_user_id', models.CharField(max_length=50)),
            ],
        ),
    ]
