# Generated by Django 2.2.4 on 2019-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20190916_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='images',
            field=models.CharField(max_length=255),
        ),
    ]
