# Generated by Django 2.2.4 on 2019-10-21 16:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20191020_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='images',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(max_length=500, upload_to='media/notes/images/')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
    ]
