# Generated by Django 2.2.4 on 2019-09-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20190922_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_delete',
            field=models.BooleanField(default=False, max_length=2),
        ),
    ]
