# Generated by Django 2.2.4 on 2019-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_notes_is_delete'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collects',
            fields=[
                ('collect_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('note_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('like_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('note_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='notes',
            name='desc',
            field=models.CharField(max_length=255),
        ),
    ]
