# Generated by Django 2.2.4 on 2019-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20190930_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_delete',
            field=models.BooleanField(default=False, max_length=2),
        ),
    ]
