# Generated by Django 2.2.4 on 2019-10-10 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20191010_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='images',
            field=models.ImageField(max_length=500, upload_to='avatars/'),
        ),
    ]
