# Generated by Django 2.2.4 on 2019-10-13 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_remove_note_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='user_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
