# Generated by Django 2.2.4 on 2019-10-13 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user_id',
        ),
    ]
