# Generated by Django 2.2.4 on 2019-10-13 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_note_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Follow',
            new_name='Like',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='follow_id',
            new_name='like_id',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='follow_user_id',
            new_name='note_id',
        ),
    ]
