# Generated by Django 2.2.4 on 2019-10-13 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20191013_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='like',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.Like'),
            preserve_default=False,
        ),
    ]
