# Generated by Django 2.2.4 on 2019-10-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_remove_note_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collect',
            fields=[
                ('collect_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('note_id', models.CharField(max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
