# Generated by Django 2.2.6 on 2019-10-16 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_follow'),
        ('notes', '0013_auto_20191016_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='note_id',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='note_id',
        ),
        migrations.RemoveField(
            model_name='collect',
            name='user_id',
        ),
        migrations.AddField(
            model_name='collect',
            name='note',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.Note'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collect',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.User'),
            preserve_default=False,
        ),
    ]
