# Generated by Django 2.2.4 on 2019-09-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=20)),
                ('user_sex', models.IntegerField(max_length=20)),
                ('user_account', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_password', models.CharField(max_length=20)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_img', models.CharField(max_length=150)),
                ('user_isdelete', models.BooleanField(default=False, max_length=2)),
                ('user_isactive', models.BooleanField(default=True, max_length=2)),
                ('token', models.CharField(max_length=50)),
                ('vcode', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
