# Generated by Django 2.2.4 on 2019-10-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('user_account', models.CharField(max_length=50)),
                ('user_sex', models.IntegerField(default=1)),
                ('user_password', models.CharField(max_length=20)),
                ('user_nickname', models.CharField(max_length=20)),
                ('user_img', models.ImageField(upload_to='media/users/user_img')),
                ('user_isdelete', models.BooleanField(default=False)),
                ('user_isactive', models.BooleanField(default=False)),
                ('token', models.CharField(max_length=50)),
                ('vcode', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('follow_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('be_follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='be_follower', to='users.User')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='users.User')),
            ],
        ),
    ]
