# Generated by Django 2.2.4 on 2019-09-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('follow_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('follow_user_id', models.CharField(max_length=20)),
            ],
        ),
    ]
