# Generated by Django 2.2.4 on 2019-09-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_sex',
            field=models.IntegerField(default=1, max_length=20),
        ),
    ]
