# Generated by Django 2.2.4 on 2019-09-30 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_notes_is_delete'),
        ('users', '0002_follows'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
    ]
