# Generated by Django 2.2.6 on 2019-10-21 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191020_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='media/users/user_img/default.jpg', upload_to='media/users/user_img'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(default='新用户', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='vcode',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
