# Generated by Django 2.2.6 on 2019-10-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20191021_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='vcode',
            field=models.CharField(default=False, max_length=50),
        ),
    ]
